### Agregar alumno
POST http://localhost:5000/alumnos
Content-Type: application/json

{
  "nombre": "Pedro",
  "notas": [6, 7, 5]
}

### Modificar alumno
PUT http://localhost:5000/alumnos/Jose
Content-Type: application/json

{
  "notas": [8, 9, 7]
}

### Consultar alumno
GET http://localhost:5000/alumnos/Jose
